/* cpu_search_main.c -- experiment CLI on top of libcylon.
 * GENERATED by tools/split_cpu_search.py: main() is verbatim from the
 * frozen cpu_search.c monolith (same flags, same prints, same flow).
 * Tiers: libcylon.so = O2 -fno-tree-vectorize (scalar),
 * libcylon_avx.so = O3 -mavx2 (avx). See CYLON-SDK.md M1. */
#include "cylon_internal.h"

int main(int argc, char **argv)
{
    const char *blob = 0, *qfile = 0, *gtfile = 0, *dumpfile = 0;
    const char *dev = "/dev/dax0.0";
    uint32_t n = 1000, k = 10, ef = 100;
    double frac = 1.0;
    int repeat = 1;
    int trace = 0;
    int pass = 0;
    int skip_stage = 0;
    int stage_dev = 0;
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "-f") && i + 1 < argc) { blob = argv[++i]; }
        else if (!strcmp(argv[i], "-q") && i + 1 < argc) { qfile = argv[++i]; }
        else if (!strcmp(argv[i], "-g") && i + 1 < argc) { gtfile = argv[++i]; }
        else if (!strcmp(argv[i], "-o") && i + 1 < argc) { dumpfile = argv[++i]; }
        else if (!strcmp(argv[i], "-w") && i + 1 < argc) { dev = argv[++i]; }
        else if (!strcmp(argv[i], "-n") && i + 1 < argc) { n = strtoul(argv[++i], 0, 0); }
        else if (!strcmp(argv[i], "-k") && i + 1 < argc) { k = strtoul(argv[++i], 0, 0); }
        else if (!strcmp(argv[i], "-e") && i + 1 < argc) { ef = strtoul(argv[++i], 0, 0); }
        else if (!strcmp(argv[i], "-R") && i + 1 < argc) { repeat = atoi(argv[++i]); }
        else if (!strcmp(argv[i], "-F") && i + 1 < argc) { frac = strtod(argv[++i], 0); }
        else if (!strcmp(argv[i], "-T")) { trace = 1; }
        else if (!strcmp(argv[i], "-S")) { skip_stage = 1; }
        else if (!strcmp(argv[i], "--stage=dev")) { stage_dev = 1; }
        else if (!strcmp(argv[i], "--stage=ft")) { stage_dev = 0; }
        else if (!strncmp(argv[i], "--poll-sleep", 12)) {
            g_poll_us = strchr(argv[i], '=')
                        ? strtoul(strchr(argv[i], '=') + 1, 0, 0) : 50;
        }
        else if (!strncmp(argv[i], "--notify=", 9)) {
            const char *v = argv[i] + 9;
            if (!strcmp(v, "poll")) {
                g_poll_us = 0;          /* v1 tight spin (default) */
            } else if (!strcmp(v, "sleep")) {
                g_poll_us = 50;         /* sleeping poll */
            } else if (!strcmp(v, "doorbell")) {
                g_db_fd = -2;       /* open /dev/cylon-db after mmap */
            } else {
                fprintf(stderr, "cpu_search: --notify must be poll|sleep|"
                        "doorbell\n");
                return 1;
            }
        }
        else {
            fprintf(stderr, "usage: %s -f blob -q queries -g gt "
                            "[-n N -k K -e EF -o dump -w dev -R repeats "
                            "-F FRAC --stage=dev|ft --poll-sleep[=us]]\n", argv[0]);
            return 1;
        }
    }
    if (!blob || !qfile || !gtfile) {
        fprintf(stderr, "usage: %s -f blob -q queries -g gt "
                        "[-n N -k K -e EF -o dump -w dev -F FRAC]\n", argv[0]);
        return 1;
    }
    setvbuf(stdout, NULL, _IONBF, 0);
    g_trace = trace;

    /* window (devdax chardev: real size lives in sysfs) */
    int fd = open(dev, O_RDWR);
    if (fd < 0) {
        fprintf(stderr, "cpu_search: open %s: %s\n", dev, strerror(errno));
        return 1;
    }
    off_t ws = lseek(fd, 0, SEEK_END);
    if (ws <= 0) {
        char p[256];
        snprintf(p, sizeof(p), "/sys/bus/dax/devices/%s/size",
                 strrchr(dev, '/') + 1);
        FILE *sf = fopen(p, "r");
        if (sf) {
            unsigned long long v = 0;
            if (fscanf(sf, "%llu", &v) == 1) {
                ws = (off_t)v;
            }
            fclose(sf);
        }
    }
    if (ws <= 0) {
        fprintf(stderr, "cpu_search: cannot determine %s size\n", dev);
        return 1;
    }
    win_sz = (uint64_t)ws;
    win = mmap(NULL, win_sz, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (win == MAP_FAILED) {
        fprintf(stderr, "cpu_search: mmap %s (%lu B): %s\n",
                dev, (unsigned long)win_sz, strerror(errno));
        return 1;
    }
    printf("window: %s = %lu MB\n", dev, (unsigned long)(win_sz >> 20));
    mb = (struct pnm_mb_s *)(win + win_sz - PNM_MB_OFF_FROM_END);

    if (g_db_fd == -2) {
        /* doorbell mode: the cylon-doorbell PCI device + cylon_doorbell.ko
         * must be up; without /dev/cylon-db this is a hard error (falling
         * back to polling would silently skew the E-M arms). */
        g_db_fd = open("/dev/cylon-db", O_RDWR);
        if (g_db_fd < 0) {
            fprintf(stderr, "cpu_search: doorbell mode: open /dev/cylon-db: "
                            "%s (insmod cylon_doorbell.ko?)\n", strerror(errno));
            return 1;
        }
        printf("doorbell: /dev/cylon-db open\n");
    }

    uint64_t blob_bytes = 0;
    if (stage_dev) {
        /* D2 device-initiated staging (PNM_OP_STAGE): the device bulk-fills
         * its cache tier from its own media; the guest pushes nothing.
         * Overrides -S (staging always runs in dev mode). Fresh boot
         * (media/maptbl empty -> coverage shortfall) or an older engine
         * (ENOSYS) falls back to the legacy first-touch push; timeout does
         * NOT fall back (the engine is still mid-job). */
        if (ping() || flush_cache()) {
            return 1;
        }
        struct stat sb;
        if (stat(blob, &sb) < 0) {
            fprintf(stderr, "cpu_search: stat %s: %s\n", blob, strerror(errno));
            return 1;
        }
        blob_bytes = (uint64_t)sb.st_size;
        uint32_t want = (uint32_t)((blob_bytes + 4095) >> 12);
        uint32_t staged_pages = 0;
        uint32_t rc = stage_device(blob_bytes, &staged_pages);
        if (rc == PNM_ST_OK && staged_pages == want) {
            printf("  device-staged blob: %u pages (%lu MB) via PNM_OP_STAGE\n",
                   staged_pages, (unsigned long)(blob_bytes >> 20));
        } else if (rc == PNM_ST_EINVAL) {
            return 1;
        } else {
            printf("  device staging covered %u/%u pages (rc=%u) -- "
                   "falling back to first-touch\n",
                   staged_pages, want, rc);
            flush_cache();
            blob_bytes = stage_file(blob, 0);
        }
    } else if (skip_stage) {
        /* -S: window pre-staged by a prior run (full residency -> all pages
         * later declared below; -S assumes -f blob file stat gives the size */
        struct stat sb;
        if (stat(blob, &sb) < 0) {
            fprintf(stderr, "cpu_search: stat %s: %s\n", blob, strerror(errno));
            return 1;
        }
        blob_bytes = sb.st_size;
    } else {
        if (ping() || flush_cache()) {
            return 1;
        }
    }

    /* stage blob + queries exactly like pnm_client */
    if (!skip_stage && !stage_dev) blob_bytes = stage_file(blob, 0);
    struct cyh1_header *hdr = (struct cyh1_header *)win;
    if (hdr->magic != CYH1_MAGIC) {
        fprintf(stderr, "cpu_search: bad CYH1 magic %08x\n", hdr->magic);
        return 1;
    }
    st.graph = win;                 /* ALL graph reads now go through DER */
    st.dim = hdr->dim;  st.count = hdr->count;  st.maxm0 = hdr->maxm0;
    st.entry_point = hdr->entry_point;
    st.entry_level = (uint8_t)hdr->entry_level;
    st.g_off_vectors = hdr->off_vectors;
    st.g_off_adj0 = hdr->off_adj0;
    st.g_off_upper = hdr->off_upper;
    st.g_off_levels = hdr->off_levels;

    uint64_t qoff = (blob_bytes + 4095) & ~4095ull;
    win_blob_bytes = blob_bytes;
    uint64_t staged = stage_file(qfile, qoff);
    printf("cpu bound: dim %u count %u maxm0 %u entry %u lvl %u "
           "(queries %lu B at window+0x%lx)\n",
           st.dim, st.count, st.maxm0, st.entry_point, st.entry_level,
           (unsigned long)staged, (unsigned long)qoff);

    st.visited = calloc(1, (st.count + 7) / 8);
    st.cand_cap = 65536; st.res_cap = 4096;
    st.cand = malloc(sizeof(struct pnm_cnd) * st.cand_cap);
    st.res = malloc(sizeof(struct pnm_cnd) * st.res_cap);
    st.qconv = malloc(sizeof(float) * 4096);

    /* ground truth: n x 10 u32 */
    FILE *gf = fopen(gtfile, "rb");
    if (!gf) {
        fprintf(stderr, "cpu_search: open %s\n", gtfile);
        return 1;
    }
    uint32_t gtrow = 10;
    uint32_t *gt = malloc((size_t)n * gtrow * 4);
    if (!gt || fread(gt, 4, (size_t)n * gtrow, gf) != (size_t)n * gtrow) {
        fprintf(stderr, "cpu_search: short read on %s\n", gtfile);
        return 1;
    }
    fclose(gf);

    uint64_t *lat = malloc((size_t)n * 8);
    struct pnm_cnd *out = malloc(sizeof(struct pnm_cnd) * k);

    /* collaborative split: [0, n_cpu) guest vCPU, [n_cpu, n) FEMU engine */
    if (k > COLLAB_KMAX) {
        fprintf(stderr, "cpu_search: k %u > COLLAB_KMAX %d\n", k, COLLAB_KMAX);
        return 1;
    }
    uint32_t n_cpu = (uint32_t)(frac * (double)n + 0.5);
    if (n_cpu > n) {
        n_cpu = n;
    }
    printf("collab split: %u CPU / %u engine (frac %.2f)\n",
           n_cpu, n - n_cpu, frac);

    g_all_ids = calloc(n, sizeof(*g_all_ids));
    g_all_d = calloc(n, sizeof(*g_all_d));
    g_all_m = calloc(n, 4);
    if (!g_all_ids || !g_all_d || !g_all_m) {
        fprintf(stderr, "cpu_search: OOM merged result arrays\n");
        return 1;
    }

    uint32_t hits = 0, n_ok = 0;
    uint64_t tot = 0;
    FILE *dfp = dumpfile ? fopen(dumpfile, "wb") : NULL;

    /* engine queries need the index bound exactly once, before the first
     * SEARCH (BIND walks the whole staged blob, so do it outside the pass
     * loop) */
    if (n_cpu < n && bind_index()) {
        return 1;
    }

    for (int pass = 0; pass < repeat; pass++) {
        hits = 0; n_ok = 0; tot = 0; g_dist = 0; g_hops = 0;
        g_e_dist = 0; g_e_hops = 0; g_e_pages = 0; g_e_ns = 0;
        uint64_t t_wall0 = now_ns();

        /* CPU worker + engine feeder run concurrently on disjoint query
         * blocks; both write disjoint lat[] slots and merged rows */
        struct collab_ctx ctx = {
            .qoff = qoff, .lat = lat, .out = out,
            .n_cpu = n_cpu, .k = k, .ef = ef,
        };
        pthread_t thr;
        bool have_thr = n_cpu > 0;
        if (have_thr && pthread_create(&thr, NULL, cpu_worker, &ctx) != 0) {
            fprintf(stderr, "cpu_search: pthread_create: %s\n",
                    strerror(errno));
            return 1;
        }

        /* main thread feeds the engine block [n_cpu, n) */
        if (engine_feeder(qoff, n, n_cpu, k, ef, lat)) {
            return 1;
        }
        if (have_thr) {
            pthread_join(thr, NULL);
        }
        uint64_t t_wall = now_ns() - t_wall0;

        /* merged scoring: recall@k + optional dump byte-gate vs engref */
        for (uint32_t qi = 0; qi < n; qi++) {
            uint32_t m = g_all_m[qi];
            n_ok++;
            if (dfp) {
                fwrite(&m, 4, 1, dfp);
                for (uint32_t j = 0; j < k; j++) {
                    fwrite(&g_all_ids[qi][j], 4, 1, dfp);
                }
            }
            const uint32_t *g = gt + (size_t)qi * gtrow;
            for (uint32_t i = 0; i < k; i++) {
                tot++;
                for (uint32_t j = 0; j < m; j++) {
                    if (g_all_ids[qi][j] == g[i]) { hits++; break; }
                }
            }
        }
        if (n) {
            printf("pass%d query 0 top-10:", pass);
            for (uint32_t i = 0; i < 10 && i < g_all_m[0]; i++) {
                printf(" (%u, %.1f)", g_all_ids[0][i], g_all_d[0][i]);
            }
            printf("\n");
        }

        /* per-worker busy times (before qsort destroys query order) */
        uint64_t cpu_sum = 0, eng_sum = 0;
        for (uint32_t i = 0; i < n_cpu; i++) {
            cpu_sum += lat[i];
        }
        for (uint32_t i = n_cpu; i < n; i++) {
            eng_sum += lat[i];
        }
        qsort(lat, n, 8, cmp_u64);
        uint64_t sum = 0;
        for (uint32_t i = 0; i < n; i++) {
            sum += lat[i];
        }
        printf("\n=== results (n=%u ok, k=%u, ef=%u) ===\n", n_ok, k, ef);
        printf("QPS        = %.1f\n", (double)n / ((double)sum / 1e9));
        printf("latency ns = p50 %lu  p90 %lu  p99 %lu  max %lu\n",
               (unsigned long)lat[n / 2], (unsigned long)lat[n * 9 / 10],
               (unsigned long)lat[n * 99 / 100], (unsigned long)lat[n - 1]);
        if (n_cpu > 0 && n_cpu < n) {
            printf("collab    : wall %.3f s  combined %.1f QPS  "
                   "(T_cpu %.3f s  T_eng %.3f s)\n",
                   (double)t_wall / 1e9, (double)n * 1e9 / (double)t_wall,
                   (double)cpu_sum / 1e9, (double)eng_sum / 1e9);
        }
        if (n_cpu) {
            printf("cpu/query: dist %.1f  hops %.1f  exec %.0f ns  "
                   "(misses not visible client-side; ~exec/40us when miss-bound)\n",
                   (double)g_dist / n_cpu, (double)g_hops / n_cpu,
                   (double)cpu_sum / n_cpu);
        }
        if (n_cpu < n) {
            uint32_t n_eng = n - n_cpu;
            printf("engine/query: dist %.1f  hops %.1f  exec %.0f ns  misses %.1f\n",
                   (double)g_e_dist / n_eng, (double)g_e_hops / n_eng,
                   (double)g_e_ns / n_eng, (double)g_e_pages / n_eng);
        }
        printf("recall@%u  = %.4f\n", k, (double)hits / tot);
        (void)verify_window(blob);
    }
    if (dfp) {
        fclose(dfp);
    }
    return 0;
}
